INSERT INTO product (name, description, code, image_url, category_id, active) VALUES
('Crucifixo Inclinado',
 'Isolamento preciso do peitoral com movimento fluido, postura correta e excelente contração muscular.',
 'BL02',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756172/BL02_d3jtfj.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Elevação Lateral Ombro',
 'Desenvolvida para definição dos ombros, oferece movimento guiado, conforto e total controle da execução.',
 'BL04',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756173/BL04_zlgovr.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Banco Scott Unilateral',
 'Foco total no desenvolvimento dos bíceps, com ergonomia avançada e execução segura.',
 'BL05',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756175/BL05_y5zeu4.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Banco Tríceps',
 'Permite trabalho independente de cada perna, corrigindo desequilíbrios musculares com conforto e controle.',
 'BL06',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756173/BL06_mqqvkz.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Remada Sentada',
 'Ativação eficiente dos dorsais com movimento natural, fluido e seguro.',
 'BL07',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756182/BL07_bongky.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Puxada Alta',
 'Desenvolvimento completo das costas com biomecânica precisa e alta estabilidade.',
 'BL08',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756178/BL08_qnktl9.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Puxada Baixa',
 'Fortalece dorsais com postura correta, conforto e execução controlada.',
 'BL09',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756177/BL09_ihukss.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Supino Reto',
 'Movimento guiado que garante eficiência, conforto e segurança no treino de peitoral.',
 'BL10',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756185/BL10_bjnpda.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Cadeira Extensora',
 'Isolamento eficiente do quadríceps com ajustes precisos e execução suave.',
 'BL11',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756183/BL11_hilh9q.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

('Flexora Vertical',
 'Ativação intensa dos posteriores de coxa, com ergonomia avançada e controle total do movimento.',
 'BL12',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756180/BL12_cgtvhy.jpg',
 (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
 true),

 ('Flexora Deitada',
  'Focado no fortalecimento individual dos membros inferiores, promovendo equilíbrio e desempenho.',
  'BL13',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756186/BL13_dwol26.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Leg Press Unilateral 45° Graus',
  'Trabalho independente das pernas com estabilidade, conforto e alto desempenho.',
  'BL14',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756190/BL14_twfwzr.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Leg Press Horizontal',
  'Desenvolvido para treinos intensos, combina robustez, conforto e máxima segurança.',
  'BL15',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756193/BL15_fzzgu1.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Supino Vertical Articulado',
  'Movimento natural e guiado para isolamento eficiente do peitoral.',
  'BL18',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756188/BL18_weldkd.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Supino Vertical Inclinado',
  'Oferece estabilidade e ergonomia para desenvolvimento seguro do peitoral.',
  'BL19',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756195/BL19_aw2bem.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Supino Guiado Reto / Inclinado',
  'Potência e estabilidade para treinos de pernas, com foco em conforto e segurança.',
  'BL20',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756191/BL20_qv22sa.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Máquina Remada Deitada',
  'Ativação profunda das costas com apoio anatômico e execução controlada.',
  'BL21',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756197/BL21_wwyrgf.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Elevação Pélvica',
  'Alternativa segura ao agachamento livre, oferecendo estabilidade e alto recrutamento muscular.',
  'BL22',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756199/BL22_g2x0dv.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Supino Reto com Alavanca',
  'Projetada para fortalecimento dos ombros, com biomecânica precisa e movimento suave.',
  'BL24',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756200/BL24_xqkx8u.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Máquina Tríceps Mergulho',
  'Desenvolvimento eficiente do tríceps com conforto, estabilidade e controle.',
  'BL25',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756202/BL25_jaw52n.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Barra Multifuncional',
  'Versatilidade para diversos exercícios, com estrutura resistente e segura.',
  'BL27',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756204/BL27_p0hs1t.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Máquina Remada Sentada com Pegada Giratória',
  'Essencial para dorsais, com execução fluida, postura correta e estabilidade.',
  'BL28',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756206/BL28_su6bj8.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Puxada Alta Cruzada',
  'Combina liberdade de carga com movimento guiado, garantindo força, controle e segurança.',
  'BL29',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756208/BL29_q1nemb.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Elevação Pélvica 3D',
  'Focada no fortalecimento de glúteos e core, com conforto e execução eficiente.',
  'BL31',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756209/BL31_xcpc1u.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Extensão de Quadril Articulado',
  'Desenvolvida para máxima ativação dos glúteos, com biomecânica avançada e alta performance.',
  'BL32',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756211/BL32_qbto2i.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Banco Extensão Lombar com Carga Articulada',
  'Fortalece glúteos e posteriores com execução estável e controle preciso.',
  'BL33',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756213/BL33_nxryhm.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Abdutora Conjugada',
  'Equipamento 2 em 1 que otimiza espaço, oferecendo eficiência e segurança no treino de quadril.',
  'BL34',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756224/BL34_gsipeg.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Máquina Ombro Articulado',
  'Movimento natural para desenvolvimento completo dos ombros, com conforto e estabilidade.',
  'BL35',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756215/BL35_bimcpq.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Máquina Supino Inclinado Articulado',
  'Foco no peitoral superior com movimento guiado e ergonomia avançada.',
  'BL36',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756216/BL36_tmplyf.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Supino Vertical Declinado',
  'Ativação independente dos lados do peitoral, garantindo equilíbrio muscular e alto desempenho.',
  'BL37',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756219/BL37_okxthd.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Puxada Alta Unilateral / Puxada Baixa Articulada',
  'Solução completa para treinos variados, com acabamento superior, robustez e versatilidade.',
  'BL38',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756220/BL38_nzwxzl.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Agachamento Sumô',
  'Treinos intensos de pernas com menor sobrecarga na coluna, oferecendo segurança e eficiência.',
  'BL53',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756222/BL53_vtqqi3.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true),

 ('Remada Curvada Guiada',
  'Fortalecimento completo das costas com execução confortável e controle total.',
  'DZ120',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756676/DZ120-_M%C3%81QUINA_REMADA_BAIXA_is3mpv.jpg',
  (SELECT category_id FROM category WHERE name = 'Articuladores Premium'),
  true)
  ON CONFLICT (code) DO NOTHING;

