INSERT INTO product (name, description, code, image_url, category_id)
VALUES
('Tireflip 180',
 'Equipamento funcional para treinos de força, potência e condicionamento físico de alta intensidade.',
 'DZ02',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756847/DZ02_aq5tgs.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Tapete Sanitizante 2 Em 1',
 'Solução prática para higienização de calçados, ideal para ambientes fitness e áreas de acesso controlado.',
 'DZ18',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756863/DZ18_kjd5fq.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Máquina Elevação De Quadril',
 'Desenvolvida para ativação máxima dos glúteos, com conforto, estabilidade e biomecânica eficiente.',
 'DZ30',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756852/DZ30_iy40cb.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Banco Ajustável Para Múltiplos Exercícios',
 'Versátil e resistente, permite diversos ângulos para treinos completos de musculação.',
 'DZ33',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756849/DZ33_lwff8z.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Trenó De Arrasto',
 'Equipamento funcional para desenvolvimento de força, potência e condicionamento cardiovascular.',
 'DZ38',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756848/DZ38_trw4ui.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Máquina De Agachamento Com Cinto',
 'Permite treinos intensos de pernas reduzindo a sobrecarga na coluna lombar.',
 'DZ53',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756853/DZ53_ajvudv.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Banco Ajustável',
 'Estrutura robusta com ajustes precisos para diferentes exercícios e níveis de treino.',
 'DZ61',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756855/DZ61_j0wpkz.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Power Rack',
 'Essencial para treinos de força, oferece segurança, estabilidade e múltiplas possibilidades de exercícios.',
 'DZ73',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756859/DZ73_gkdnsc.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Banco Olímpico Reto',
 'Projetado para cargas elevadas, com máxima estabilidade e segurança no supino reto.',
 'DZ76',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756857/DZ76_gxyga7.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

('Máquina De Agachamento Pendulo Articulado',
 'Proporciona movimento guiado e natural, com alto recrutamento muscular dos membros inferiores.',
 'DZ80C',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756861/DZ80C_rugz4c.jpg',
 (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Suspiro Reto, Inclinado E Declinado',
  'Versatilidade para treinos completos de peitoral, com ergonomia e estabilidade.',
  'DZ83',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756865/DZ83_tbkrlq.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Máquina De Puxada Alta',
  'Foco no desenvolvimento dos dorsais, com execução fluida e postura correta.',
  'DZ91',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756866/DZ91_fipqzj.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Flexora Ajoelhada Articulada',
  'Isolamento eficiente dos posteriores de coxa com conforto e controle biomecânico.',
  'DZ94',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756868/DZ94_tkgixt.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Máquina De Treino Para Glúteos',
  'Equipamento específico para fortalecimento e definição dos glúteos, com execução segura.',
  'DZ97',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756870/DZ97_voxiag.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Abdutor Em Pé',
  'Ativação eficaz do quadril e glúteos, com movimento natural e postura correta.',
  'DZ110',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756872/DZ110_rzjjdg.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Máquina Hip Trust Em Pé (Glúteo)',
  'Ideal para fortalecimento dos glúteos, oferecendo estabilidade e alto desempenho.',
  'DZ111',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770756876/DZ111_imt3v9.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Reto (Flat Bench)',
  'Essencial para exercícios livres, com estrutura reforçada e design funcional.',
  'TB36',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757208/TB36-_BANCO_RETO_FLAT_BENCH_m6lezp.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Abdominal Ajustável',
  'Permite variação de inclinação para treinos completos de abdômen com conforto.',
  'TB37',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757209/TB37-_BANCO_ABDOMINAL_AJUSTAV%C3%89L_x8kjvp.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Multiuso',
  'Versátil e resistente, atende diferentes exercícios em ambientes profissionais.',
  'TB38',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757211/TB38-_BANCO_MULTIUSO_clw4nm.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco De Musculação Ajustável',
  'Estrutura robusta com múltiplas regulagens para máxima versatilidade de treino.',
  'TB39',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757213/TB39-_BANCO_DE_MUSCULA%C3%87%C3%83O_AJUSTAV%C3%89L_wicqxo.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Supino Declinado Olímpico',
  'Desenvolvido para treinos intensos, garantindo estabilidade e segurança.',
  'TB41',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757216/TB41-_BANCO_SUPINO_DECLINADO_OLIMP%C3%8DCO_djoioh.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Olímpico Inclinado',
  'Foco no peitoral superior, com estrutura reforçada para cargas elevadas.',
  'TB42',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757217/TB42-_BANCO_OL%C3%8DMPICO_INCLINADO_dzie5q.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Supino Reto Olímpico',
  'Equipamento profissional para treinos de força, com máxima durabilidade.',
  'TB43',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757220/TB43-_BANCO_SUPINO_RETO_OLIMPICO_o9cqtp.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Treino De Bíceps',
  'Isolamento eficiente do bíceps com postura correta e conforto.',
  'TB44',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757223/TB44-_BANCO_TREINO_DE_BICEPS_swmquv.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

 ('Banco Extensão Lombar',
  'Fortalece lombar e core, promovendo estabilidade e prevenção de lesões.',
  'TB45',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757224/TB45-_BANCO_EXTENSAO_LOMBAR_lpqaef.jpg',
  (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Equipamento Para Ginástica',
   'Ideal para exercícios funcionais, alongamentos e atividades corporais diversas.',
   'TB46',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757226/TB46-_EQUIPAMENTO_PARA_GINASTICA_vwebwy.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Equipamento Elevação Vertical Joelho E Paralela',
   'Desenvolvimento de core, membros superiores e força funcional.',
   'TB47',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757229/TB47-_EQUIPAMENTO_ELEVA%C3%87%C3%83O_VERTICAL_JOELHO_E_PARALELA_keuh26.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Equipamento Vertical Para Treino De Força',
   'Estrutura completa para exercícios de peso corporal e força.',
   'TB48',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757230/TB48-_EQUIPAMENTO_VERTICAL_PARA_TREINO_DE_FOR%C3%87A_a6s909.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Rack-Suporte Para Halteres (Dumbbells)',
   'Organização eficiente e segura dos halteres, otimizando espaço.',
   'TB49',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757233/TB49-_RACK-SUPORTE_PARA_HALTERES_DUMBBELLS_pxn0qn.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Rack Para Agachamento Livre',
   'Projetado para treinos de força com segurança e estabilidade.',
   'TB50',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757236/TB50-_RACK_PARA_AGACHAMENTO_LIVRE_u5a798.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Banco Olímpico Para Desenvolvimento Sentado',
   'Ideal para treinos de ombro com cargas elevadas e postura correta.',
   'TB51',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757238/TB51-BANCO_OL%C3%8DMPICO_PARA_DESENVILVIMENTO_SENTADO_arxhyl.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Suporte Para Anilhas',
   'Mantém o ambiente organizado e facilita o acesso às cargas.',
   'TB54',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757244/TB54-_SUPORTE_PARA_ANILHAS_atub9y.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Suporte Para Barras De Peso Fixas',
   'Armazenamento prático e seguro para barras de musculação.',
   'TB55',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757241/TB55-_SUPORTE_PARA_BARRAS_DE_PESO_FIXAS_g4vcmn.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina Leg Press Vertical 45° Graus',
   'Alta performance para treino de pernas, com estabilidade e conforto.',
   'TB56',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757245/TB56-_M%C3%81QUINA_LEG_PRESS_45_GRAUS_gbjm9i.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Equipamento Agachamento E Parte Inferior',
   'Desenvolvido para fortalecimento completo dos membros inferiores.',
   'TB57',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757248/TB57-_EQUIPAMENTO_AGACHAMENTO_E_PARTE_INFERIOR_tt4kpe.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Equipamento Carga De Peso Livre',
   'Versátil para diferentes exercícios com uso de anilhas.',
   'TB59',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757250/TB59-_EQUIPAMENTO_CARGA_DE_PESO_LIVRE_kwejtd.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina De Remo Em T (T-Bar Row)',
   'Ativação intensa das costas, com execução estável e eficiente.',
   'TB61',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757253/TB61-_M%C3%81QUINA_DE_REMO_EM_T_T-BAR_ROW_oqvp31.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina Elevação De Panturrilha Sentada',
   'Isolamento eficaz das panturrilhas com conforto e controle.',
   'TB62',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757255/TB62-_M%C3%81QUINA_ELEVA%C3%87%C3%83O_DE_PANTURRILHA_SENTADA_b6icxy.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina Smith',
   'Barra guiada para treinos seguros, ideal para usuários de todos os níveis.',
   'TB63',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757258/TB63-_M%C3%81QUINA_SMITH_yqiyd9.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina De Agachamento Articulado',
   'Movimento guiado que garante segurança e alto recrutamento muscular.',
   'TB65',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757260/TB65-_M%C3%81QUINA_DE_AGACHAMENTO_ARTICULADO_odgiw7.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Rack Para Dumbbells De 3 Níveis',
   'Organização prática, resistente e ideal para academias profissionais.',
   'TB67',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757263/TB67-_RACK_PARA_DUMBBELLS_DE_3_N%C3%8DVEIS_cdvvzx.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Power Rack Tb68',
   'Modelo reforçado para treinos de força avançados, com máxima segurança.',
   'TB68',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757266/TB68-_POWER_RACK_TB68_wjpkwu.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina Antebraço',
   'Desenvolvimento específico dos músculos do antebraço com ergonomia.',
   'TB69',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757268/TB69-_M%C3%81QUINA_ANTIBRA%C3%87O_v0gbpn.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Equipamento Para Alongamento',
   'Ideal para mobilidade, flexibilidade e prevenção de lesões.',
   'TB71',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757270/TB71-EQUIPAMENTO_PARA_ALONGAMENTO_itmerl.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina De Agachamento Smith 3D',
   'Tecnologia que permite movimentos mais naturais e seguros.',
   'TB73',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757273/TB73-_M%C3%81QUINA_DE_AGACHAMENTO_SMITH_3D_lfgzqz.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Estação De Barra Fixa, Paralela E Elevação De Perna',
   'Treino completo de força funcional e peso corporal em um único equipamento.',
   'TB80',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757275/TB80-_ESTA%C3%87%C3%83O_DE_BARRA_FIXA_PARALELA_E_ELEVA%C3%87%C3%83O_DE_PERNA_d3f0vm.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Banco Supino Inclinado',
   'Projetado para treinos focados no peitoral superior, com estabilidade.',
   'TB86',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757278/TB86-_BANCO_SUPINO_INCLINADO_buql3m.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Máquina Smith And Squat (Agachamento Smith)',
   'Combina versatilidade e segurança para treinos de força completos.',
   'TB87',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757279/TB87-_M%C3%81QUINA_SMITH_AND_SQUAT_AGACHAMENTO_SMITH_vxnmaf.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star')),

  ('Suporte Para Halteres De 2 Níveis',
   'Solução compacta e resistente para organização de halteres.',
   'TB88',
   'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770757282/TB88-_SUPORTE_PARA_HALTERES_DE_02_N%C3%8DVEIS_n5ggnk.jpg',
   (SELECT category_id FROM category WHERE name = 'Livre Articulados Star'))
   ON CONFLICT (code) DO NOTHING;


