INSERT INTO product (name, description, code, image_url, category_id, active)
VALUES
('Máquina Supino Vertical',
 'Desenvolvida para oferecer máxima ativação do peitoral, com movimento guiado, estabilidade e segurança em cada repetição.',
 'TY01',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739423/TY01_aqyvnl.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Máquina Desenvolvimento De Ombro',
 'Garante força, conforto e biomecânica precisa para um desenvolvimento completo e seguro dos ombros.',
 'TY02',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739434/TY02_ygqzux.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Remada Sentada',
 'Ideal para fortalecimento das costas, proporciona postura correta, fluidez de movimento e alto controle durante o treino.',
 'TY03',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739423/TY03_x5njmx.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Crucifixo / Fly',
 'Versatilidade em um único equipamento, permitindo treinar peitoral e dorsal com eficiência, conforto e segurança.',
 'TY04',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739423/TY04_xwhxoj.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Banco Scott',
 'Isolamento preciso do bíceps com carga seletorizada, garantindo execução controlada e excelente rendimento muscular.',
 'TY05',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739425/TY05_vg4o0z.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Banco Tríceps Press',
 'Foco total no desenvolvimento do tríceps, com ergonomia avançada e estabilidade para treinos intensos e seguros.',
 'TY06',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739433/TY06_jmqz7n.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Máquina Elevação Lateral Ombro',
 'Projetada para definição dos ombros, oferece movimento guiado, conforto e controle total da execução.',
 'TY07',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739426/TY07_vlwzso.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Pull Down',
 'Essencial para o treino de costas, com pegada confortável, movimento natural e alta estabilidade.',
 'TY08',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739428/TY08_ialsai.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Puxada Baixa',
 'Proporciona ativação completa dos dorsais, com execução fluida, postura correta e segurança.',
 'TY09',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739426/TY09_b9cp8g.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Máquina Abdominal E Lombar',
 'Equipamento conjugado que fortalece o core e a região lombar, garantindo equilíbrio muscular e segurança.',
 'TY11',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739427/TY11_hbqgya.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Cadeira Extensora',
 'Isolamento eficaz do quadríceps, com ajustes precisos, conforto e controle total do movimento.',
 'TY13',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739427/TY13_exzggk.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Cadeira Flexora Sentada',
 'Desenvolvida para o fortalecimento dos posteriores de coxa, com postura correta e execução suave.',
 'TY14',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739430/TY14_jbsnjx.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Mesa Flexora Deitada',
 'Máxima ativação dos posteriores de coxa, com apoio confortável e biomecânica eficiente.',
 'TY15',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739429/TY15_r9azpg.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Leg Press Horizontal',
 'Estrutura robusta e estável para treinos intensos de pernas, oferecendo segurança e alto desempenho.',
 'TY16',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739442/TY16_pu8iiw.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Glúteo Extensão de Quadril',
 'Foco total no fortalecimento dos glúteos, com movimento controlado e execução segura.',
 'TY18',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739431/TY18_m18lrl.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Cadeira Adutora',
 'Trabalha a musculatura interna da coxa com ergonomia, conforto e controle preciso da carga.',
 'TY19',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739432/TY19_qiqvvr.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Cadeira Abdutora',
 'Equipamento versátil que permite alternar exercícios com facilidade, garantindo eficiência e segurança.',
 'TY20',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739434/TY20_a7npah.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Graviton',
 'Permite o treino de puxadas com segurança e controle, ideal para diferentes níveis de condicionamento.',
 'TY24',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739436/TY24_k8yvtb.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Extensora / Flexora Sentada Conjugada',
 'Solução inteligente para treino completo de membros inferiores, otimizando espaço sem perder performance.',
 'TY25',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739436/TY25_x3xyen.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Cadeira Extensora / Flexora Sentada Conjugada',
 'Versatilidade para treino de pernas, combinando dois movimentos essenciais com ergonomia e estabilidade.',
 'TY28',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739440/TY28_wugiq2.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Puxada Alta / Pulley',
 'Clássico indispensável para dorsais, com movimento suave, controle e alta segurança.',
 'TY33',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739422/TY33_mlvlhf.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Máquina Abdominal',
 'Desenvolvida para fortalecer o core com conforto, estabilidade e execução precisa.',
 'TY35',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739422/TY35_uy9qjx.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Máquina de Tríceps Mergulho',
 'Ideal para o desenvolvimento de tríceps e peitoral, com movimento guiado e postura correta.',
 'TY36',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739422/TY36_ze4xed.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
),
('Máquina Elevação Pélvica',
 'Focada no fortalecimento de glúteos e core, garante estabilidade, conforto e execução eficiente.',
 'TY39',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770739441/TY39_jz9bv2.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha Alfa'),
 TRUE
)
ON CONFLICT (code) DO NOTHING;
