INSERT INTO product (name, description, code, image_url, category_id, active)
VALUES
('Crossover Angular Profissional',
 'Liberdade total de movimento para treinos funcionais e de força, com estrutura robusta, ajustes precisos e alto desempenho profissional.',
 'HS01',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS01_u6tb2w.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Crucifixo',
 'Equipamento conjugado que permite trabalhar dois grupos musculares com eficiência, conforto e execução segura.',
 'HS02',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738626/HS02_ydqmz0.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Crossover',
 'Isolamento preciso do peitoral, com movimento fluido, postura correta e excelente contração muscular.',
 'HS03',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS03_p5u6wi.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Desenvolvimento Ombro',
 'Desenvolvida para ativação eficiente da parte superior do peitoral, oferecendo estabilidade e biomecânica avançada.',
 'HS04',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS04_w8khst.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Elevação Lateral Ombro',
 'Ideal para definição dos ombros, proporciona movimento guiado, conforto e total controle da execução.',
 'HS05',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS05_wbdx6a.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Pull Down',
 'Treino eficiente de dorsais com controle de carga, fluidez e ergonomia para máxima segurança.',
 'HS06',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS06_sylujq.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Puxada Alta',
 'Clássico indispensável para costas, com pegadas confortáveis e execução natural.',
 'HS07',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS07_eeq1hu.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Puxada Baixa Máquina',
 'Versatilidade em um único equipamento, permitindo treinos completos de dorsais com praticidade e segurança.',
 'HS08',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738628/HS08_ey9nfd.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Scott Máquina',
 'Isolamento eficaz do bíceps, garantindo postura correta, conforto e alto rendimento muscular.',
 'HS09',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738628/HS09_kzzeg7.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Máquina Tríceps Press',
 'Desenvolvimento preciso do tríceps, com movimento controlado e excelente estabilidade.',
 'HS10',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738629/HS10_yo54pj.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Graviton',
 'Equipamento conjugado que otimiza espaço e oferece eficiência para treinos de braços e peitoral.',
 'HS11',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738631/HS11_wmimba.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Leg Press Horizontal Sentado',
 'Potência e estabilidade para treinos intensos de membros inferiores, com foco em segurança e conforto.',
 'HS12',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738630/HS12_g6tnx4.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Cadeira Extensora',
 'Isolamento eficiente do quadríceps, com ajustes precisos e execução suave.',
 'HS13',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738631/HS13_ttsa9t.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Cadeira Flexora Sentada',
 'Focada no fortalecimento dos posteriores de coxa, com biomecânica precisa e apoio confortável.',
 'HS14',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738631/HS14_srcol9.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Mesa Flexora Deitada',
 'Proporciona isolamento máximo dos posteriores, com conforto e segurança durante a execução.',
 'HS15',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738631/HS15_h7tufc.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Cadeira Abdutora',
 'Trabalha musculatura interna e externa do quadril em um único equipamento, com fluidez e ergonomia.',
 'HS16',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738633/HS16_yp25hg.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Cadeira Adutora',
 'Versatilidade e eficiência para fortalecimento do quadril, com ajustes simples e movimento controlado.',
 'HS17',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738634/HS17_lzuvy3.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Panturrilha Vertical',
 'Desenvolvida para treinos intensos de panturrilha, com estabilidade, conforto e alta resistência.',
 'HS18',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738634/HS18_u5q41j.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Apolete',
 'Ideal para treinos funcionais de quadril e glúteos, oferecendo ampla variação de exercícios.',
 'HS20',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738634/HS20_f116cb.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Máquina Extensão Lombar',
 'Fortalece a região lombar com postura correta, conforto e total segurança.',
 'HS21',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738635/HS21_opqinu.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Máquina Abdominal Crunch Profissional',
 'Treinos intensos de core com isolamento eficiente, conforto e controle total do movimento.',
 'HS22',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738635/HS22_zd4xdg.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Puxada Baixa',
 'Projetada para fortalecimento das costas superiores, com execução precisa e estrutura robusta.',
 'HS23',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738636/HS23_rnvvyy.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Cadeira Extensora / Flexora Sentada Conjugada',
 'Equipamento conjugado que permite treino completo de membros inferiores com praticidade e ergonomia.',
 'HS31',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738637/HS31_f7at4o.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Adutora / Abdutora Conjugada',
 'Equipamento versátil para abdutores e adutores, com conforto e fácil ajuste de carga.',
 'HS32',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738637/HS32_hp0hje.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Puxada Alta / Baixa Conjugada',
 'Dois exercícios essenciais em um único equipamento, garantindo eficiência e segurança.',
 'HS33',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738638/HS33_dffrbo.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Scott Máquina',
 'Controle total de carga para um treino preciso e confortável de bíceps.',
 'HS34',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738638/HS34_nyr1yw.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Supino / Desenvolvimento Ombro Conjugada',
 'Dois movimentos em um só equipamento, oferecendo versatilidade, estabilidade e alto desempenho.',
 'HS35',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738639/HS35_c80dez.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Máquina Lombar',
 'Treino completo do core e lombar, promovendo equilíbrio muscular e segurança.',
 'HS36',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738639/HS36_fkbjl6.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Extensora / Flexora Deitada Conjugada',
 'Permite trabalhar quadríceps e posteriores em um único equipamento, com ajustes rápidos e conforto.',
 'HS37',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738640/HS37_qrrudw.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Máquina Elevação Pélvica',
 'Focada no fortalecimento de glúteos e core, com execução estável e eficiente.',
 'HS38',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738640/HS38_cenk8h.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Banco Lombar com Carga',
 'Projetada para fortalecimento seguro da região lombar, com controle de carga e ergonomia.',
 'HS39',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738641/HS39_huxdd7.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Crossover',
 'Alta versatilidade para treinos de força e funcionais, com ajustes precisos e movimento fluido.',
 'HS85',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS85_nnxto6.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
),
('Cross Angular Multifuncional',
 'Solução completa para treinos variados, ideal para otimizar espaço sem abrir mão da performance.',
 'HS89',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770738627/HS89_kzbciw.jpg',
 (SELECT category_id FROM category WHERE name = 'Linha SW Máquinas'),
 TRUE
)
ON CONFLICT (code) DO NOTHING;
