INSERT INTO product (name, description, code, image_url, category_id, active)
VALUES
('Supino Reto Vertical',
 'Desenvolvida para máxima ativação do peitoral superior, com movimento articulado que garante fluidez, conforto e segurança.',
 'TM01',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755276/TM01_k0db01.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Puxada Alta Articulada',
 'Equipamento versátil que combina força e ergonomia, proporcionando treinos eficientes e controlados.',
 'TM02',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755276/TM02_pgufqj.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Leg Press Sentado Unilateral',
 'Oferece estabilidade e conforto para treinos intensos de pernas, com foco em segurança e alto desempenho.',
 'TM03',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755277/TM03_o21bui.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Supino Vertical Inclinado',
 'Potência e robustez para membros inferiores, garantindo execução segura mesmo em altas cargas.',
 'TM04',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755278/TM04_ekowfz.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Pull Down Articulado',
 'Movimentos naturais e biomecânica avançada para treinos funcionais, seguros e eficientes.',
 'TM05',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755280/TM05_vsrzzp.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Remada Sentada',
 'Permite trabalho independente de cada lado do corpo, promovendo equilíbrio muscular e força com controle total.',
 'TM06',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755282/TM06_xfscjv.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Supino Vertical Declinado',
 'Ideal para ativação ampla do peitoral, oferecendo estabilidade, conforto e execução precisa.',
 'TM07',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755282/TM07_xlgjac.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Máquina De Agachamento Lounge',
 'Projetada para movimentos profundos e seguros, proporcionando alto recrutamento muscular com estabilidade.',
 'TM08',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755284/TM08_yu2svm.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Agachamento Smith',
 'Treinos de força com movimento guiado, oferecendo segurança, controle e versatilidade.',
 'TM09',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755285/TM09_zzvcqo.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Banco de Ombro',
 'Estrutura reforçada para treinos pesados de ombro, com máxima estabilidade e durabilidade.',
 'TM10',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755287/TM10_pv2bqi.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

 ('Banco Lombar',
  'Equipamento 2 em 1 para fortalecimento do core e lombar, com ajustes ergonômicos e conforto.',
  'TM11',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755288/TM11_coz0xn.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Remada Vertical Articulada',
  'Desenvolvimento eficiente das costas com movimento natural, fluido e biomecanicamente correto.',
  'TM13',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755290/TM13_zbfspc.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Suporte Para Anilhas Olímpicas',
  'Organização, praticidade e segurança para o ambiente fitness profissional.',
  'TM14',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755291/TM14_i8a5eh.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Supino Super Inclinado Articulado',
  'Foco total no peitoral superior e ombros, com movimento guiado e conforto avançado.',
  'TM15',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755293/TM15_u3yqan.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Cadeira Extensora Articulada',
  'Correção de desequilíbrios musculares com execução controlada, confortável e segura.',
  'TM17',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755327/TM17_d0sc9k.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Mesa Flexora Deitada Articulada',
  'Isolamento preciso dos posteriores de coxa, com apoio anatômico e fluidez no movimento.',
  'TM18',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755295/TM18_vj5r2x.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Banco Scott',
  'Isolamento máximo do bíceps, garantindo postura correta e maior eficiência no treino.',
  'TM20',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755298/TM20_aqfgau.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Máquina Desenvolvimento De Ombro',
  'Oferece estabilidade e biomecânica precisa para fortalecimento completo dos ombros.',
  'TM21',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755299/TM21_eeqjjx.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Alavanca Para Agachamento / Avanço Multifuncional',
  'Versatilidade total em um único equipamento, ideal para otimizar espaço sem perder performance.',
  'TM22',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755301/TM22_kigs3r.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Máquina De Panturrilha Sentada',
  'Treinos intensos de panturrilha com conforto, estabilidade e alta resistência estrutural.',
  'TM23',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755302/TM23_gjgp24.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Supino Reto Articulado',
  'Desenvolvimento eficiente do peitoral com conforto, fluidez e controle do movimento.',
  'TM28',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755309/TM28_agxa5u.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Banco Scott Articulado',
  'Isolamento preciso do bíceps com movimento guiado e ergonomia avançada.',
  'TM29',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755310/TM29_vwbtmf.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Rack De Agachamento',
  'Base sólida para treinos de força, oferecendo segurança, estabilidade e versatilidade.',
  'TM31',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755312/TM31_etddvz.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Banco De Supino Reto',
  'Clássico indispensável para treinos com pesos livres, com estrutura robusta e segura.',
  'TM34',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755322/TM34_m4ui0p.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Cadeira Extensora Articulada',
  'Proporciona execução suave e controle preciso, maximizando o trabalho do quadríceps.',
  'TM37',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755328/TM37_wjzjtf.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

('BBanco Supino Reto com Trava',
 'Projetado para altas cargas, garantindo resistência, estabilidade e durabilidade.',
 'TM38',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755313/TM38_ze0ntv.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Leg Press Vertical (90° Graus)',
 'Treino intenso de pernas com máxima ativação muscular e segurança estrutural.',
 'TM39',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755315/TM39_n7goxw.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Banco Supino Inclinado com Trava',
 'Ideal para variação de estímulos no peitoral, com conforto e suporte profissional.',
 'TM42',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755317/TM42_wg01yu.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Banco Abdominal Regulável',
 'Permite ajustes de inclinação para treinos abdominais completos e eficientes.',
 'TM45',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755318/TM45_ost4ns.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Banco Supino Multifuncional',
 'Versátil e resistente, ideal para diversos exercícios com pesos livres.',
 'TM46',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755320/TM46_wn9g6g.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Máquina Elevação Lateral Ombro Deitada',
 'Isolamento eficiente dos deltoides com postura estável e execução controlada.',
 'TM48',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755323/TM48_ditc9c.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Estante Para Dumbbells',
 'Acabamento resistente que aumenta durabilidade, proteção e estética dos halteres.',
 'TM50',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755330/TM50_izq84q.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Banco Fixo',
 'Projetado para treinos específicos de ombros e peitoral superior, com máxima estabilidade.',
 'TM51',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755332/TM51_nop9nr.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Banco Abdominal Declinado',
 'Permite maior intensidade nos treinos de core, com conforto e segurança.',
 'TM55',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755333/TM55_bdse5t.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Banco Crucifixo Inclinado',
 'Ativação precisa do peitoral superior com movimento articulado e ergonomia avançada.',
 'TM56',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755335/TM56_jhvnwv.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Máquina Elevação Lateral Articulada',
 'Movimento natural e fluido para definição dos ombros, com controle total.',
 'TM58',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755336/TM58_qlrlhf.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Cadeira Abdutora Articulada',
 'Fortalecimento do quadril com conforto, estabilidade e execução segura.',
 'TM59',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755338/TM59_mrx6in.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Rack de Banda Montada',
 'Organização prática e segura para barras, otimizando o espaço da academia.',
 'TM61',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755325/TM61_pgvcox.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Flexora Vertical Articulada',
 'Isolamento máximo dos posteriores, com independência de movimentos e alta eficiência.',
 'TM66',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755340/TM66_mlxlzq.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Máquina Tríceps Mergulho',
 'Desenvolvimento intenso de tríceps com conforto, estabilidade e biomecânica precisa.',
 'TM67',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755342/TM67_eha18f.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Máquina Pulôver Articulada',
 'Ativa dorsais e peitoral com movimento amplo, fluido e altamente eficiente.',
 'TM68',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755343/TM68_lhvcqf.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Cadeira Adutora Articulada',
 'Focada no fortalecimento do quadril, com execução confortável e controlada.',
 'TM70',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755349/TM70_fvtek1.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

('Agachamento Squat',
 'Oferece alto recrutamento muscular com estabilidade e segurança no movimento.',
 'TM71',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755346/TM71_efhlgs.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
 TRUE),

 ('Máquina Abdominal Articulada',
  'Treinos de core eficientes com suporte, conforto e controle de execução.',
  'TM72',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755352/TM72_erjwsk.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Banco Supino Declinado com Trava',
  'Ideal para treinos intensos de peitoral inferior, com estrutura reforçada.',
  'TM73',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755353/TM73_z13prb.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Prancha Abdominal',
  'Desenvolvido para exercícios avançados de core, com estabilidade e resistência.',
  'TM75',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755348/TM75_hutqnr.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Paralela Abdominal com Prancha',
  'Treino completo de core em um único equipamento, com conforto e eficiência.',
  'TM77',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755354/TM77_wk3qvd.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Panturrilha Vertical',
  'Versatilidade para membros inferiores, combinando força, estabilidade e segurança.',
  'TM80',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755356/TM80_pkoagi.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Banco De Musculação Ajustável',
  'Permite múltiplas posições para treinos variados, com estrutura robusta.',
  'TM87',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755358/TM87_cvmrm9.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Banco Lombar',
  'Fortalece lombar e core com ajustes ergonômicos e execução segura.',
  'TM89',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755359/TM89_zi8vi8.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Gaiola de Agachamento Multifuncional',
  'Máxima segurança e liberdade para treinos de força pesada.',
  'TM90',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755361/TM90_nyfreo.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Leg Press 45° Graus',
  'Combinação ideal de conforto e potência para desenvolvimento de pernas.',
  'TM91',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755364/TM91_be1ef8.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Agachamento Sissy',
  'Isolamento intenso de quadríceps com suporte e estabilidade no movimento.',
  'TM92',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755362/TM92_xw2eqs.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Cadeira Posterior',
  'Desenvolvida para fortalecimento dos posteriores de coxa com ergonomia avançada.',
  'TM93',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755366/TM93_pn6tcv.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Rotação De Tronco Em Pé',
  'Ideal para fortalecimento do core e estabilidade corporal, com movimento guiado.',
  'TM94',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755369/TM94_j16hn3.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Equipamento Multifuncional',
  'Solução completa para treinos variados, otimizando espaço e investimento.',
  'TM95',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755368/TM95_klmm0y.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Rack de Barras Montadas',
  'Organização e segurança para armazenamento de barras.',
  'TM96',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755386/TM96_ysdyjp.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Banco De Musculação Ajustável',
  'Versátil e resistente, permite múltiplas posições para treinos variados, oferecendo conforto, estabilidade e segurança em cada exercício.',
  'TM97',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755372/TM97_q4bmdq.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Máquina Leg Press Vertical 45º Graus',
  'Máxima intensidade para membros inferiores com estrutura reforçada.',
  'TM99',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755371/TM99_f6h0zt.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Barra Paralela Abdominal',
  'Treinos completos com peso corporal, ideal para força e condicionamento.',
  'TM100',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755374/TM100_ktwdir.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Gaiola de Força Power Rack',
  'Estrutura profissional para treinos pesados com total segurança.',
  'TM101',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755376/TM101_nlbtct.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Gaiola Para Agachamento Multifuncional',
  'Versátil e compacto, ideal para treinos de força com liberdade e controle.',
  'TM102',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755378/TM102_cxixvl.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Agachamento Articulada',
  'Movimento natural e biomecânico para agachamentos mais seguros.',
  'TM111',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755379/TM111_zwb5ez.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Máquina Abdução Articulada',
  'Treino intenso de glúteos com carga livre, estabilidade e alto desempenho.',
  'TM112',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755382/TM112_t1hv5m.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Puxada Alta Articulada',
  'Ativação eficiente dos dorsais com movimento fluido e conforto.',
  'TM113',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755383/TM113_tfjgyr.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Máquina Agachamento Hack',
  'Isolamento potente de pernas com estabilidade e suporte total.',
  'TM114',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755384/TM114_tn23ue.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE),

 ('Máquina Elevação Articulada',
  'Desenvolvida para máxima ativação dos glúteos, com conforto e segurança.',
  'TM118',
  'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770755388/TM118_pgumdd.jpg',
  (SELECT category_id FROM category WHERE name = 'Plate Loaded Star'),
  TRUE)
  ON CONFLICT (code) DO NOTHING;



