INSERT INTO product (name, description, code, image_url, category_id, active)
VALUES
('Wide Chest Press',
 'Desenvolvida para máxima ativação do peitoral, oferece amplitude ampla de movimento, estabilidade e execução segura.',
 'TA05',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754935/TA05_iifqit.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Supino Sentado Inclinado',
 'Ideal para o trabalho do peitoral superior, com postura correta, conforto e movimento controlado.',
 'TA10',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754936/TA10_fc625o.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Supino Articulado',
 'Movimento natural e guiado que garante eficiência, conforto e segurança no desenvolvimento do peitoral.',
 'TA15',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754936/TA15_tdw0mm.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Plate Loaded (Carregamento De Anilhas)',
 'Equipamentos de alta performance que permitem progressão de carga com estabilidade, robustez e controle total.',
 'TA20',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754942/TA20_va65ny.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Remada Baixa Articulada',
 'Ativação precisa das costas com movimento fluido, postura correta e excelente estabilidade.',
 'TA25',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754938/TA25_gjm02o.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Remo Sentado',
 'Treino completo de dorsais com execução confortável, controle do movimento e segurança.',
 'TA30',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754939/TA30_ncnvq4.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Desenvolvimento De Ombros',
 'Fortalecimento eficiente dos ombros com biomecânica precisa e estrutura estável.',
 'TA35',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754940/TA35_ts90fi.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Rear Kick',
 'Focado no fortalecimento dos glúteos, proporciona movimento controlado, conforto e alta eficiência.',
 'TA40',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754943/TA40_cozdzg.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Leg Press',
 'Potência e estabilidade para treinos intensos de membros inferiores, com foco em segurança e desempenho.',
 'TA50',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754946/TA50_q9rb3q.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Máquina Alavanca Bíceps',
 'Isolamento preciso do bíceps com sistema de alavanca que garante fluidez e execução correta.',
 'TA65',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754945/TA65_rvnljk.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Máquina Extensão De Pernas',
 'Isolamento eficiente do quadríceps, com ajustes precisos e movimento suave.',
 'TA70',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754947/TA70_hcntff.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE),

('Flexão De Pernas Em Pé',
 'Trabalho focado dos posteriores de coxa, com postura ergonômica e execução segura.',
 'TA75',
 'https://res.cloudinary.com/dhnaj9mdn/image/upload/v1770754949/TA75_afpg1v.jpg',
 (SELECT category_id FROM category WHERE name = 'Plate Loaded Gold'),
 TRUE)
 ON CONFLICT (code) DO NOTHING;
